<?php

use Illuminate\Database\Seeder;

class MoviesTableSeeder extends Seeder {

	public function run()
	{
		$existing = DB::table('movies')->count();
		if( !$existing )
		{
			$movies = [
				// title,sort-title,released,image,running,rating,certificate,format,studio,bio
				['47 Ronin','47 Ronin','2013','47_Ronin_Front.jpg','128','6','5','2','18','A band of samurai set out to avenge the death and dishonor of their master at the hands of a ruthless shogun.'],
				['Alice in Wonderland','Alice In Wonderland','2010','Alice_In_Wonderland_Front.jpg','108','6','3','2','4','Nineteen-year-old Alice returns to the magical world from her childhood adventure, where she reunites with her old friends and learns of her true destiny: to end the Red Queen&#039;s reign of terror.'],
				['Alien','Alien 1','1979','ALien_1_Front.jpg','116','8','7','2','1','In space,no-one can hear you scream'],
				['Aliens','Alien 2','1986','Alien_2_Front.jpg','131','8','7','2','1','This time its war'],
				['Alien 3','Alien 3','1992','Alien_3_Front.jpg','109','6','7','2','1','Ripley continues to be stalked by a savage alien, after her escape pod crashes on a prison planet.'],
				['Alien Resurrection','Alien 4','1997','Alien_4_Front.jpg','104','5','7','2','1','Two centuries after her death, Ellen Ripley is revived as a powerful human/alien hybrid clone who must continue her war against the aliens.'],
				['Fight Club','Fight Club','1999','Fight_Club_Front.jpg','125','10','7','2','1','The first rule of Fight Club is: you do not talk about Fight Club'],
				['Die Hard','Die Hard 1','1990','Die_Hard_Front.jpg','108','8','7','1','1','Yippee Kayaye MaggotFarmer'],
				['The Matrix','Matrix 1','1999','The_Matrix_Front.jpg','123','8','6','1','19','He is the one'],
				['Star Wars','Star Wars 4','1977','Star_Wars_4_Front.jpg','128','10','2','2','1','The Force will be with you, always'],
				['Avengers Assemble','Avengers 1','2012','Avengers_1_Front.jpg','137','8','4','2','5','When an unexpected enemy emerges that threatens global safety and security, Nick Fury finds himself needing a team that can pull the world back from the brink of disaster. Cue Iron Man, The Incredible Hulk, Captain America, Black Widow and Hawkeye - The Avengers.'],
				['The Amazing Spiderman','Amazing Spiderman 1','2012','Amazing_Spiderman_1_Front.jpg','136','6','4','2','3','A wise-cracking, taller Spider-Man. This time he&#039;s up against Lizardman.'],
				['Titanic','Titanic','1998','Titanic_1450359229.jpg','194','7','4','1','1','Big ship hits an iceberg. Jack tells Rose not to let go, but she does after he freezes to death in the water; then watches him sink to the bottom of the Atlantic Ocean. '],
				['Angels with Dirty Faces','Angels with Dirty Faces','1938','Angels_With_Dirty_Faces_1450361371.jpg','97','9','3','1','19','A priest tries to stop a gangster from corrupting a group of street kids.'],
				['White Heat','White Heat','1949','White_Heat_1450367282.jpg','114','9','6','1','19','A psychopathic criminal with a mother complex makes a daring break from prison and leads his old gang in a chemical plant payroll heist. Shortly after the plan takes place, events take a crazy turn. &quot;Made it Ma, top of the world!&quot;'],
				['50 First Dates','50 First Dates','2004','50_First_Dates_1450367805.jpg','99','6','5','1','3','Henry Roth is a man afraid of commitment up until he meets the beautiful Lucy. They hit it off and Henry think he&#039;s finally found the girl of his dreams, until he discovers she has short-term memory loss and forgets him the very next day.'],
				['The Lion King','Lion King','1994','Lion_King_1450368557.jpg','89','9','2','2','4','A young lion Prince is cast out of his pride by his cruel uncle, who claims he killed his father. While the uncle rules with an iron fist, the prince grows up beyond the savannah, living by a philosophy: No worries for the rest of your days. But when his past comes to haunt him,the young Prince must decide his fate: will he remain an outcast, or face his demons and become what he needs to be?'],
				['Jurassic Park','Jurassic Park 1','1993','Jurassic_Park_1_1450369841.jpg','127','8','3','2','18','Huge advancements in scientific technology have enabled a mogul to create an island full of living dinosaurs. John Hammond has invited four individuals, along with his two grandchildren, to join him at Jurassic Park. But will everything go according to plan? A park employee attempts to steal dinosaur embryos, critical security systems are shut down and it now becomes a race for survival with dinosaurs roaming freely over the island.'],
				['Jurassic Park: The Lost World','Jurassic Park 2','1997','Jurassic_Park_2_1450369988.jpg','129','6','3','2','18','A research team is sent to the Jurassic Park Site B island to study the dinosaurs there while another team approaches with another agenda.'],
				['Jurassic Park 3','Jurassic Park 3','2001','Jurassic_Park_3_1450370366.jpg','92','5','3','2','18','A decidedly odd couple with ulterior motives convince Dr. Alan Grant to go to Isla Sorna (the second InGen dinosaur lab.), resulting in an unexpected landing; and unexpected new inhabitants on the island.'],
				['Jurassic World','Jurassic World 4','2015','Jurassic_World_4_1450370490.jpg','124','7','5','2','18','A new theme park is built on the original site of Jurassic Park. Everything is going well until the park&#039;s newest attraction--a genetically modified giant stealth killing machine--escapes containment and goes on a killing spree.'],
				['Akira','Akira','1988','Akira_1450373794.jpg','124','8','4','1','20','A secret military project endangers Neo-Tokyo when it turns a biker gang member into a rampaging psionic psychopath that only two kids and a group of psionics can stop.'],
				['Argo','Argo','2012','Argo_1450374473.jpg','120','7','6','2','19','Acting under the cover of a Hollywood producer scouting a location for a science fiction film, a CIA agent launches a dangerous operation to rescue six Americans in Tehran during the U.S. hostage crisis in Iran in 1980.'],
				['Avatar','Avatar 1','2009','Avatar_1_1450374586.jpg','162','7','5','2','1','A paraplegic marine dispatched to the moon Pandora on a unique mission becomes torn between following his orders and protecting the world he feels is his home.'],
				['Back to the Future','Back to the Future 1','1985','Back_To_The_Future_1_1450374793.jpg','116','9','3','2','18','A young man is accidentally sent thirty years into the past in a time-traveling DeLorean invented by his friend, Dr. Emmett Brown, and must make sure his high-school-age parents unite in order to save his own existence.'],
				['Back to the Future 2','Back to the Future 2','1989','Back_To_The_Future_2_1450374891.jpg','108','7','3','2','18','Marty McFly has only just gotten back from the past, when he is once again picked up by Dr. Emmett Brown and sent through time to the future. Marty&#039;s job in the future is to pose as his own son to prevent him from being thrown in prison. Unfortunately, things get worse when the future changes the present.'],
				['Back to the Future 3','Back to the Future 3','1990','Back_To_The_Future_3_1450374978.jpg','118','8','3','2','18','Stranded in 1955, Marty McFly receives written word from his friend, Doctor Emmett Brown, as to where can be found the DeLorean time machine. However, an unfortunate discovery prompts Marty to go to his friend&#039;s aid. Using the time machine, Marty travels to the old west where his friend has run afoul of a gang of thugs and has fallen in love with a local schoolteacher. Using the technology from the time, Marty and Emmett devise one last chance to send the two of them back to the future.'],
				['American - The Bill Hicks Story','American The Bill Hicks Story','2009','American_The_Bill_Hicks_Story_1450375278.jpg','102','7','6','2','22','Photo-animated feature documentary, uniquely narrated by the 10 people who knew Bill best.'],
				['The Bourne Identity','Bourne 1','2002','Bourne_1_1450375808.jpg','119','8','5','2','18','Based very loosely on Robert Ludlum&#039;s novel, the Bourne Identity is the story of a man whose wounded body is discovered by fishermen who nurse him back to health. He can remember nothing and begins to try to rebuild his memory based on clues such as the Swiss bank account, the number of which, is implanted in his hip. He soon realizes that he is being hunted and takes off with Marie on a search to find out who he is and why he is being hunted.'],
				['The Bourne Supremacy','Bourne 2','2004','Bourne_2_1450375918.jpg','108','9','5','2','18','After escaping from the emotional and physical pain he previously encountered. Jason Bourne and his girlfriend Marie begin a new life as far away as possible. But when an assassination attempt on Bourne goes horribly wrong, Bourne must re-enter the life he wanted to leave behind, in order to find out the truth why they are still after him.'],
				['The Bourne Ultimatium','Bourne 3','2007','Bourne_3_1450376066.jpg','115','8','5','2','18','Bourne is once again brought out of hiding, this time inadvertently by London-based reporter Simon Ross who is trying to unveil Operation Blackbriar--an upgrade to Project Treadstone--in a series of newspaper columns. Bourne sets up a meeting with Ross and realizes instantly they&#039;re being scanned. Information from the reporter stirs a new set of memories, and Bourne must finally, ultimately, uncover his dark past whilst dodging The Company&#039;s best efforts in trying to eradicate him.'],
				['Batman Begins','Batman 5','2005','Batman_5_1450376492.jpg','140','7','5','2','19','After training with his mentor, Batman begins his war on crime to free the crime-ridden Gotham City from corruption that the Scarecrow and the League of Shadows have cast upon it.'],
				['The Dark Knight','Batman 6','2008','Batman_6_1450376574.jpg','152','9','5','2','19','When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, the caped crusader must come to terms with one of the greatest psychological tests of his ability to fight injustice.'],
				['The Dark Knight Rises','Batman 7','2012','Batman_7_1450376745.jpg','164','6','5','2','19','Eight years after the Joker&#039;s reign of anarchy, the Dark Knight is forced to return from his imposed exile to save Gotham City from the brutal guerrilla terrorist Bane with the help of the enigmatic Selina.'],
				['Black Swan','Black Swan','2010','Black_Swan_1450379048.jpg','108','7','6','2','23	','A committed dancer wins the lead role in a production of Tchaikovsky&#039;s Swan Lake only to find herself struggling to maintain her sanity.'],
				['Bad Lieutenant','Bad Lieutenant','2009','Bad_Lieutenant_1450379307.jpg','122','5','7','2','8','Terence McDonagh is a drug- and gambling-addled detective in post-Katrina New Orleans investigating the killing of five Senegalese immigrants.'],
				['The Fifth Element','Fifth Element','1997','Fifth_Element_1450452578.jpg','126','7','3','1','24','In the colorful future, a cab driver unwittingly becomes the central figure in the search for a legendary cosmic weapon to keep Evil and Mr Zorg at bay.'],
				['The Cabin in the Woods','Cabin in the Woods','2012','Cabin_In_The_Woods_1450460205.jpg','95','8','6','2','8','Five friends go for a break at a remote cabin in the woods, where they get more than they bargained for. Together, they must discover the truth behind the cabin in the woods.'],
				['Candyman','Candyman','1992','Candyman_1450460417.jpg','99','7','7','2','26','The Candyman, a murderous soul with a hook for a hand, is accidentally summoned to reality by a skeptic grad student researching the monster&#039;s myth.'],
				['Carlito&#039;s Way','Carlitos Way','1993','Carlitos_Way_1450460535.jpg','144','6','7','2','18','A Puerto Rican former convict, just released from prison, pledges to stay away from drugs and violence despite the pressure around him and lead on to a better life outside of N.Y.C.'],
				['Chronicle','Chronicle','2012','Chronicle_1450461167.jpg','84','7','3','2','1','Whilst attending a party, three high school friends gain superpowers after making an incredible discovery underground. Soon, though, they find their lives spinning out of control and their bond tested as they embrace their darker sides.'],
				['Collateral','Collateral','2004','Collateral_1450461287.jpg','120','7','6','2','12','A cab driver finds himself the hostage of an engaging contract killer as he makes his rounds from hit to hit during one night in Los Angeles. He must find a way to save both himself and one last victim.'],
				['Clerks','Clerks','1994','Clerks_1450461391.jpg','92','7','7','2','27','A day in the lives of two convenience clerks named Dante and Randal as they annoy customers, discuss movies, and play hockey on the store roof.'],
				['The Crow','Crow','1994','Crow_1450461564.jpg','102','7','7','2','27','A poetic guitarist Eric Draven is brought back to life by a crow a year after he and his fianc&eacute;e are murdered. The crow guides him through the land of the living, and leads him to his killers: knife thrower Tin-tin, drugetic Funboy, car buff T-Bird, and the unsophisticated Skank. One by one, Eric gives these thugs a taste of their own medicine. However their leader Top-Dollar, a world-class crime lord who will dispatch his enemies with a Japanese sword and joke about it later, will soon learn the legend of the crow and the secret to the vigilante&#039;s invincibility.'],
				['Crouching Tiger, Hidden Dragon','Crouching Tiger Hidden Dragon','2000','Crouching_Tiger_Hidden_Dragon_1450461733.jpg','120','10','4','2','21','Crouching Tiger Hidden Dragon is a timeless story that takes place in QING China when miracles were credible and spirits and gods were present in man&#039;s world. It is not unbelievable that zen warriors float through the air, skim the water and battle in trees and on rooftops. Pain, revenge and duty are the stuff that bind us in this world and are the main plot line of the movie, but in the afterlife love and faith linger on.'],
				['The Doors','Doors','1991','Doors_1450530360.jpg','140','7','7','2','15','The story of the famous and influential 1960s rock band and its lead singer and composer, Jim Morrison, from his days as a UCLA film student in Los Angeles, to his untimely death in Paris, France at age 27 in 1971.'],
				['Dredd','Dredd','2012','Dredd_1450530497.jpg','95','7','7','2','21','In a violent, futuristic city where the police have the authority to act as judge, jury and executioner, a cop teams with a trainee to take down a gang that deals the reality-altering drug, SLO-MO.'],
				['Drive','Drive','2011','Drive_1450530597.jpg','100','8','7','2','22','A mysterious Hollywood stuntman and mechanic moonlights as a getaway driver and finds himself trouble when he helps out his neighbor.'],
				['The Legend of Drunken Master','Drunken Master 2','1994','Drunken_Master_2_1450530748.jpg','102','8','4','2','28','A young martial artist is caught between respecting his pacifist father&#039;s wishes or stopping a group of disrespectful foreigners from stealing precious artifacts.'],
				['Enchanted','Enchanted','2007','Enchanted_1450530897.jpg','107','7','3','2','4','A princess, who is prepared to be wed, is sent away to New York by an evil queen, where she falls in love with a lawyer.'],
				['Escape from New York','Escape from New York','1981','Escape_From_New_York_1450531091.jpg','99','6','6','2','21','In 1997, when the US President crashes into Manhattan, now a giant maximum security prison, a convicted bank robber is sent in for a rescue.'],
				['Django Unchained','Django Unchained','2012','Django_Unchained_1450531360.jpg','165','8','7','2','29','With the help of a German bounty hunter, a freed slave sets out to rescue his wife from a brutal Mississippi plantation owner.'],
				['District 9','District 9','2009','District_9_1450531510.jpg','112','8','6','2','15','An extraterrestrial race forced to live in slum-like conditions on Earth suddenly finds a kindred spirit in a government agent who is exposed to their biotechnology.'],
				['Get Smart','Get Smart','2008','Get_Smart_1450531596.jpg','110','6','5','2','19','A highly intellectual but socially awkward spy is tasked with preventing a terrorist attack from a Russian spy agency'],
				['Ghostbusters','Ghostbusters','1984','Ghostbusters_1450531699.jpg','105','9','3','2','3','Three odd-ball scientists get kicked out of their cushy positions at a university in New York City where they studied the occult. They decide to set up shop in an old firehouse and become Ghostbusters, trapping pesky ghosts, spirits, haunts, and poltergeists for money. They wise-crack their way through the city, and stumble upon a gateway to another dimension, one which will release untold evil upon the city. The Ghostbusters are called on to save the Big Apple'],
				['Guardians of the Galaxy','Guardians of the Galaxy','2014','Guardians_Of_The_Galaxy_1450531849.jpg','121','8','5','2','5','After stealing a mysterious orb in the far reaches of outer space, Peter Quill from Earth, is now the main target of a manhunt led by the villain known as Ronan the Accuser. To help fight Ronan and his team and save the galaxy from his power, Quill creates a team of space heroes known as the Guardians of the Galaxy to save the world.'],
				['Harry Potter and the Philosopher&#039;s Stone','Harry Potter 1','2001','Harry_Potter_1_1450535276.jpg','152','7','3','2','19','Rescued from the outrageous neglect of his aunt and uncle, a young boy with a great destiny proves his worth while attending Hogwarts School of Witchcraft and Wizardry.'],
				['Harry Potter and the Chamber of Secrets','Harry Potter 2','2002','Harry_Potter_2_1450535388.jpg','161','7','3','2','19','Harry ignores warnings not to return to Hogwarts, only to find the school plagued by a series of mysterious attacks and a strange voice haunting him.'],
				['Harry Potter and the Prisoner of Azkaban','Harry Potter 3','2004','Harry_Potter_3_1450535483.jpg','142','7','3','2','19','It&#039;s Harry&#039;s third year at Hogwarts; not only does he have a new &quot;Defense Against the Dark Arts&quot; teacher, but there is also trouble brewing. Convicted murderer Sirius Black has escaped the Wizards&#039; Prison and is coming after Harry.'],
				['Harry Potter and the Goblet of Fire','Harry Potter 4','2005','Harry_Potter_4_1450535598.jpg','157','7','4','2','19','Harry finds himself mysteriously selected as an under-aged competitor in a dangerous tournament between three schools of magic.'],
				['Harry Potter and the Order of the Phoenix','Harry Potter 5','2007','Harry_Potter_5_1450535691.jpg','138','6','4','2','19','With their warning about Lord Voldemort&#039;s return scoffed at, Harry and Dumbledore are targeted by the Wizard authorities as an authoritarian bureaucrat slowly seizes power at Hogwarts.'],
				['Harry Potter and the Half-Blood Prince','Harry Potter 6','2009','Harry_Potter_6_1450535792.jpg','153','6','4','2','19','As Harry Potter begins his sixth year at Hogwarts, he discovers an old book marked as &quot;the property of the Half-Blood Prince&quot; and begins to learn more about Lord Voldemort&#039;s dark past.'],
				['Harry Potter and the Deathly Hallows 1','Harry Potter 7','2010','Harry_Potter_7_1450535901.jpg','146','5','4','2','19','As Harry races against time and evil to destroy the Horcruxes, he uncovers the existence of three most powerful objects in the wizarding world: the Deathly Hallows.'],
				['Harry Potter and the Deathly Hallows 2','Harry Potter 8','2011','Harry_Potter_8_1450536034.jpg','130','7','4','2','19','Harry, Ron and Hermione search for Voldemort&#039;s remaining Horcruxes in their effort to destroy the Dark Lord as the final battle rages on at Hogwarts.'],
				['The Haunted Mansion','Haunted Mansion','2003','Haunted_Mansion_1450536223.jpg','87','5','3','2','4','A realtor and his wife and children are summoned to a mansion, which they soon discover is haunted, and while they attempt to escape, he learns an important lesson about the family he has neglected.'],
				['The Hustler','Hustler','1961','Hustler_1450536419.jpg','134','6','6','2','1','&quot;Fast&quot; Eddie Felson is a small-time pool hustler with a lot of talent but a self-destructive attitude. His bravado causes him to challenge the legendary &quot;Minnesota Fats&quot; to a high-stakes match, but he loses in a heartbreaking marathon. Now broke and without his long-time manager, Felson faces an uphill battle to regain his confidence and his game.'],
				['Hugo','Hugo','2011','Hugp_1450536872.jpg','126','6','1','2','12','Set in 1930s Paris, an orphan who lives in the walls of a train station is wrapped up in a mystery involving his late father and an automaton.'],
				['The Hunger Games','Hunger Games 1','2012','Hunger_Games_1_1450537000.jpg','142','7','4','2','8','Katniss Everdeen voluntarily takes her younger sister&#039;s place in the Hunger Games, a televised competition in which two teenagers from each of the twelve Districts of Panem are chosen at random to fight to the death.'],
				['The Hunger Games: Catching Fire','Hunger Games 2','2013','Hunger_Games_2_1450537104.jpg','146','7','4','2','8','Katniss Everdeen and Peeta Mellark become targets of the Capitol after their victory in the 74th Hunger Games sparks a rebellion in the Districts of Panem.'],
				['The Hunger Games: Mockingjay 1','Hunger Games 3','2014','Hunger_Games_3_1450537185.jpg','123','6','4','2','8','Katniss Everdeen is in District 13 after she shatters the games forever. Under the leadership of President Coin and the advice of her trusted friends, Katniss spreads her wings as she fights to save Peeta and a nation moved by her courage.'],
				['I, Robot','I, Robot','2004','I,_Robot_1450537389.jpg','115','7','4','2','1','In 2035 a technophobic cop investigates a crime that may have been perpetrated by a robot, which leads to a larger threat to humanity.'],
				['I Love You Phillip Morris','I Love You Phillip Morris','2009','I_Love_You_Phillip_Morris_1450537513.jpg','98','7','6','2','21','A cop turns con man once he comes out of the closet. Once imprisoned, he meets the second love of his life, whom he&#039;ll stop at nothing to be with.'],
				['Inglourious Basterds','Inglourious Basterds','2009','Inglourious_Bastards_1450537642.jpg','153','8','7','2','18','In Nazi-occupied France during World War II, a plan to assassinate Nazi leaders by a group of Jewish U.S. soldiers coincides with a theatre owner&#039;s vengeful plans for the same.'],
				['Inception','Inception','2010','Inception_1450537767.jpg','148','8','4','2','19','A thief who steals corporate secrets through use of the dream-sharing technology is given the inverse task of planting an idea into the mind of a CEO.'],
				['Iron Man','Iron Man 1','2008','Iron_Man_1_1450538181.jpg','126','7','4','1','5','After being held captive in an Afghan cave, an industrialist creates a unique weaponized suit of armor to fight evil.'],
				['Iron Man 2','Iron Man 2','2010','Iron_Man_2_1450537848.jpg','124','6','4','2','5','ith the world now aware of his identity as Iron Man, Tony Stark must contend with both his declining health and a vengeful mad man with ties to his father&#039;s legacy'],
				['Iron Man 3','Iron Man 3','2013','Iron_Man_3_1450537933.jpg','130','6','4','2','5','When Tony Stark&#039;s world is torn apart by a formidable terrorist called the Mandarin, he starts an odyssey of rebuilding and retribution.'],
				['Kick-Ass','Kick Ass','2010','Kick_Ass_1450538295.jpg','117','8','6','2','8','Dave Lizewski is an unnoticed high school student and comic book fan who one day decides to become a super-hero, even though he has no powers, training or meaningful reason to do so.'],
				['Looper','Looper','2012','Looper_1450538393.jpg','119','6','6','2','21','In 2074, when the mob wants to get rid of someone, the target is sent into the past, where a hired gun awaits - someone like Joe - who one day learns the mob wants to &#039;close the loop&#039; by sending back Joe&#039;s future self for assassination.'],
				['The Lord of the Rings: The Fellowship of the Ring','Lord of the Rings 1','2001','Lord_Of_The_Rings_1_1450538489.jpg','178','8','4','2','10','An ancient Ring thought lost for centuries has been found, and through a strange twist in fate has been given to a small Hobbit named Frodo. When Gandalf discovers the Ring is in fact the One Ring of the Dark Lord Sauron, Frodo must make an epic quest to the Cracks of Doom in order to destroy it! However he does not go alone. He is joined by Gandalf, Legolas the elf, Gimli the Dwarf, Aragorn, Boromir and his three Hobbit friends Merry, Pippin and Samwise.'],
				['The Lord of the Rings: The Two Towers','Lord of the Rings 2','2002','Lord_Of_The_Rings_2_1450538621.jpg','179','9','4','2','10','While Frodo and Sam edge closer to Mordor with the help of the shifty Gollum, the divided fellowship makes a stand against Sauron&#039;s new ally, Saruman, and his hordes of Isengard.'],
				['The Lord of the Rings: The Return of the King','Lord of the Rings 3','2003','Lord_Of_The_Rings_3_1450538754.jpg','201','8','4','2','10','Gandalf and Aragorn lead the World of Men against Sauron&#039;s army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.'],



			];

			array_map( function( $movie ) {
				$now = date("Y-m-d H:i:d",strtotime('now'));
				DB::table('movies')->insert([
					'movie_name' => $movie[0],
					'movie_sort_name' => $movie[1],
					'movie_release_date' => $movie[2],
					'movie_image_path' => $movie[3],
					'movie_running_time' => $movie[4],
					'movie_my_rating' => $movie[5],
					'movie_certificate_id'=> $movie[6],
					'movie_format_id' => $movie[7],
					'movie_studio_id' => $movie[8],
					'movie_bio' => $movie[9],
					'created_at' => $now,
					'updated_at' => $now
				]);
			},$movies);

		} // end of if

	} // end of method

} // end of class
